# Generated by Django 5.1.6 on 2025-03-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['day'], 'verbose_name': 'Рабочее время', 'verbose_name_plural': 'Рабочее время'},
        ),
    ]
