# Generated by Django 5.1.6 on 2025-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20250303_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['day_order'], 'verbose_name': 'Рабочее время', 'verbose_name_plural': 'Рабочее время'},
        ),
        migrations.AddField(
            model_name='workinghours',
            name='day_order',
            field=models.IntegerField(default=0, editable=False, verbose_name='Порядок дня'),
        ),
    ]
