# Generated by Django 5.1.6 on 2025-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_workinghours_options_workinghours_day_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={},
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='closing_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='day',
            field=models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='day_order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
