# Generated by Django 5.1.6 on 2025-02-19 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.userprofile', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='flowers',
            field=models.ManyToManyField(to='orders.flower', verbose_name='Цветы'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.userprofile', verbose_name='Пользователь'),
        ),
    ]
