# Generated by Django 5.1.6 on 2025-02-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
