# Generated by Django 5.1.6 on 2025-02-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_flower_image'),
        ('orders', '0003_remove_userprofile_user_delete_notificationlog_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flower',
        ),
        migrations.AlterField(
            model_name='order',
            name='flowers',
            field=models.ManyToManyField(to='catalog.flower', verbose_name='Цветы'),
        ),
    ]
