# Generated by Django 5.1.6 on 2025-02-22 15:31

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(upload_to=catalog.models.flower_image_upload_path, verbose_name='Изображение'),
        ),
    ]
